#!/usr/bin/env python

import shutil
from pathlib import Path

import stactools.panama_copc.stac
from pystac import CatalogType

root = Path(__file__).parents[1]
examples = root / "examples"

    #"https://smithsonian.dataone.org/datasets/ALS_Panama_2023/01_Agua_Salud_Alfagia/02_LAZ_Unclassified/230527_163013.laz",
collection = stactools.panama_copc.stac.create_collection()
item = stactools.panama_copc.stac.create_item(
    source="tests/data/230526_200655.copc.laz",
    destination=str(
        examples
        / "230526_200655.json"
    )
)
collection.add_item(item)
collection.normalize_hrefs(str(examples))
collection.make_all_asset_hrefs_relative()
if examples.exists():
    shutil.rmtree(examples)
    examples.mkdir()
collection.save(CatalogType.SELF_CONTAINED)
